name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    # environment: producao
    # Comentei o environment porque ele não está disponível para repositórios privados na conta gratuita
    # E o meu repositório só fica público após entregar o trabalho

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.3.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Imports
        run: ./resources-import.sh
        continue-on-error: true

      - name: Terraform Plan
        run: |
          terraform plan \
          -var="aws_account_id=${AWS_ACCOUNT_ID}" \
          -var="db_url=${DATASOURCE_URL}" \
          -var="db_username=${DATASOURCE_USERNAME}" \
          -var="db_password=${DATASOURCE_PASSWORD}" \
          -out=tfplan

      - name: Terraform Apply
        run: terraform apply "tfplan"
